[package]
name = "nettap"
version = "0.1.0"
authors = ["Ben Lipton <ben.lipton@gmail.com>"]
edition = "2018"

[dependencies]
bytes = "0.4.12"
failure = "0.1.5"
futures = "0.1.28"
quicli = "0.4.0"
structopt = "0.2.18"
tokio = "0.1.22"
